### ISSUE TITLE
Could you explain what exactly is E3 compared to E4

### ISSUE THREAD

**Issue by C4J** [RemainSoftware/e3#1]
I have figured out it does not mean Eclipse versions beginning with 3.x compared to 4.x so can you explain what it refers to please.

**Comment by wimjongman** [comment]
E3 vs E4 refers to the way of programming used to create stand-alone programs using the Eclipse framework.

## Terminology
First, let's define some terminology.

* Stand-Alone program
This is a program that you run on your computer, like eclipse.exe or outlook.exe. 
* Rich Client 
This is a stand-alone program with a user interface like trees and tables and buttons and such as opposed to command-line programs like `dir` that you use in a shell, or services that do their work completely in the background.
* Eclipse Rich Client Platform (RCP)
The Eclipse RCP makes it very easy to create rich clients in Java. A good example of an Eclipse RCP application is the Eclipse IDE itself. However, there are thousands of programs based on Eclipse RCP [like for instance DBeaver](https://en.wikipedia.org/wiki/DBeaver) which are business applications of any other type.

## E3
E3 is the original way of creating an Eclipse RCP program. The inventors of Eclipse envisioned that Eclipse itself takes care of UI elements like Views, Editors, Menus, Perspectives, Wizards, Tables, Trees, Help, etc.. but that all content (like a specific java editor or the outline view) should come from so-called `plugins` that use `extension points` that would allow developers like you and me to hook our own stuff into Eclipse.

Heck, we could even drop all Java stuff and show only our own content and package it like it had nothing to do with Eclipse.

## E4
Around 2008, people realized that a program like Eclipse can also be expressed as a model [1] using the highly successful EMF (Eclipse Modelling Framework) technology. 

Instead of using extension points, it was thought that a program could be described in an XML model and that a `renderer` would take that model and visualize it. This was a mind-blowing concept because it meant that a rich client program could literally be created on the fly, very similar to a browser. By poking into the model the UI could be changed at runtime.

At that time, other technologies were also becoming very popular like `dependency injection` (e.g. guice), `services` (SOA), and `java annotations`.

The team took all of these new concepts and started creating E4.


## E3 vs E4 programming constructs
Here is a comparison of some of the most important differences in E3 and E4 programming.

### Java API v.s. Dependency Injection
E3 is built on an extensive (and therefore complex) Java API. E4 exposes that API without having to know how to navigate it. For example, to get the Eclipse Selection Service the following is coded: 

#### E3
`ISelectionService selService = PlatformUI.getWorkbench().getActiveWorkbenchWindow().getSelectionService()`

#### E4
`
@Inject
ISelectionService selService;`

You would still need to know that the ISelectionService exists but fetching it is now delegated to the injection framework which always gives you the correct instance in the correct context.

### No inheritance
The E3 UI elements like Views have to extend the IViewPart interface. In E4 this is done with annotations. The advantage is that you don't have to depend on the Eclipse classes. You would still have to depend on the annotations but they can be used outside of the Eclipse framework in another SWT application.

Take a look at how a view is defined in E3 vs E4

#### E3
First, the E3 application would have to extend the `org.eclipse.ui.views` `extension point`, and then your view class would be coded like this:

     public class MyView extends ViewPart {
	 @Override
 	public void createPartControl(Composite pArg0) {
 	}

	 @Override
 	public void setFocus() {
	 }
    }

#### E4
In E4 you can point from the model to an annotated POJO.

    public class ExampleView {
       @Inject
       public ExampleView(Composite parent) {
       }
    }

## Eclipse IDE
The Eclipse IDE has been converted from an E3 application to an E4 application with a first public release Eclipse 4.0 [2]. Eclipse is using the mythical `Compatibility Layer` to convert E3 extensions points into the equivalent model elements. This results in an identical application but now running on a different technology.

Eclipse itself is still developed using the E3 concepts relying on the 'Compatibility Layer' to manipulate the underlying model.

People extending the Eclipse IDE mostly use the E3 model (using extension points)

`Pure E4` applications are applications that exclusively rely on the model. These applications tend to be applications that are not extending the Eclipse IDE. 




[1] https://www.eclipse.org/e4/resources/e4-whitepaper.php
[2] https://www.eclipse.org/helios/eclipse-sdk-4.0/
